backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

logo_url: https://github.com/david-mccullough/realgoodtouring/blob/main/src/images/logo.png?raw=true

media_folder: static/img
public_folder: ../../static/img

collections:
  - name: "tour"
    label: "Tour"
    extension: "md"
    folder: "content/tours"
    create: true
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Thumbnail",
          name: "Image",
          widget: "image",
          hint: "Please try to keep below 200kb! https://tinypng.com/ is a great tool for image compression.",
          required: false,
          default: "",
        }
      - {
          label: "Go-live Time",
          name: "liveTime",
          widget: "datetime",
          picker_utc: true,
          hint: "PST (tours are sorted based on this field)",
        }
      - label: "Events"
        name: "events"
        widget: "list"
        summary: "{{date | date('MM/DD/YY')}} - {{fields.location}}"
        fields:
          - {
              label: "Date",
              name: "date",
              widget: "datetime",
              required: false,
              format: "MM/DD/YY",
              picker_utc: true,
            }
          - {
              label: "Location",
              name: "location",
              widget: "string",
              hint: "e.g. Los Angeles, CA",
            }
          - { label: "Venue Name", name: "venueName", widget: "string" }
          - { label: "Tickets Link", name: "ticketsLink", widget: "string" }
          - {
              label: "Sold Out",
              name: "isSoldOut",
              widget: "boolean",
              required: false,
              default: false,
            }
          - {
              label: "Note",
              name: "note",
              required: false,
              default: "",
              widget: "string",
              hint: "e.g. *Venue Change",
            }
  - name: "vip"
    label: "VIP Q&A"
    extension: "md"
    folder: "content/vip"
    create: true
    editor:
      preview: true
    fields:
      - label: "Sections"
        name: "sections"
        widget: "list"
        fields:
          - { label: "Question", name: "question", widget: "string" }
          - { label: "Answer", name: "answerMarkdown", widget: "markdown" }
